<a href="https://colab.research.google.com/github/21400126/Pytorch/blob/master/1_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
'''
autograd : 자동미분을 수행하는 토치의 핵심 패키지
forward 방향으로 수행하는 모든 연산을 기억, backward로 연산들을 재생

.requires_grad : if I set its attribute True , it starts to track all operations on it => True속성을 가지고 있다면 계산은 추적된다

.backward() : when I finish my computation, then have all the gradients computed automatically , if want to compute the derivatives
스칼라(한개의 element를 가지고 있는) 형태 => 파라미터 필요 x / otherwise, 텐서의 matching shape를 gradient의 인자로 지정해야한다

.grad : The gradient for this tensor will be accumulated into this attribute
=> backward() 계산한 후, 변수에 대한 그라디언트는 이 속성에 누적된다.

.detach() : to stop a tensor from tracking history / to detach it from the computation history, and to prevent future computation

torch.no_grad() : to prevent tracking history, using memory, i can also wrap the code block  // when evaluating a model it's so helpful

Function => 각 변수는 Tensor를 생성한 Function을 참조하는 .grad_fn속성을 가지고 있다

requires_grad_ 는 이미 존재하는 텐서의 requires_grad플래그를 내부에서 변경함 / 입력 플래그 명시하지 않은 경우 기본적으로 True
torch.autograd = engine for computing vector-Jacobian product
'''

import torch

x = torch.ones(2,2, requires_grad = True)
print(x)  

y = x+2
print(y)                  #grad_fn =<AddBackward0> 라는 값도 같이 출력됨

print(y.grad_fn)       # operation의 결과로써 생겼기 때문에, grad_fn을 가진다


z= y * y * 3
out = z.mean()           # what is z.mean()? => to average whole tensor

print(z)
print(out)                 # contains single scalar => why? => .mean()을 통해 scalar값으로 만들어 주었음
 
a=torch.randn(2,2)
print("a=",a)

a = ((a*3)/(a-1))
print(a.requires_grad)#False

a.requires_grad_(True)
print(a.requires_grad)#True

print (a)

b=(a*a).sum()       
print(b)      

#out.backward() == out.backward(torch.tensor(1.))

out.backward()           # 모든 값이 4.5인 2x2 행렬
print(x.grad)             


x = torch.randn(3, requires_grad = True)

y= x*2

while y.data.norm() < 1000:
  y = y * 2
  
print(y) 

v = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
print(x.grad) #None


x.backward(v)
print(x.grad)# 이 값 왜 v인지 몰겠음

y.backward(v)
print(x.grad) 

print(x.requires_grad)             #True
print((x**2).requires_grad)        #True

with torch.no_grad() :  # 이것으로 래핑하여 requires_grad = True속성이 명시된 autograd가 텐서의 추적기록에 남지 않게 한다
  print((x**2).requires_grad)         #False
  
with torch.no_grad() :  
  print(x.requires_grad)         # 이건 왜 True? => 아무 연산도 진행되지 않은 것은 True를 default 값으로 한다


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)
a= tensor([[ 0.7123, -0.3707],
        [-1.9919, -1.6206]])
False
True
tensor([[-7.4273,  0.8113],
        [ 1.9973,  1.8552]], requires_grad=True)
tensor(63.2536, grad_fn=<SumBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
tensor([1025.0343,  128.9029, -319.9389], grad_fn=<MulBackward0>)
None
tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])
tensor([5.1300e+01, 5.1300e+02, 5.1300e-02])
True
True
False
True
